version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt update

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn install
          command: |
            yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build
          command: |
            yarn build

      - run:
          name: Run tests
          command: |
            yarn test
