version: 2
jobs:
    build:
        docker:
            - image: cricleci/node:latest

        steps:
            - checkout

            - run:
                name: Install dependencies
                command: |
                    apt update

            - run:
                name: Yarn install
                command: |
                    yarn install

            - run:
                name: Run tests
                command: |
                    yarn test
