version: 2
jobs:
    build:
        docker:
            - image: cimg/node:15.14.0

        steps:
            - checkout

            - run:
                name: Install dependencies
                command: |
                    sudo apt update

            - run:
                name: Yarn install
                command: |
                    yarn install

            - run:
                name: Run tests
                command: |
                    yarn test
